client:
	g++ -g -o client client.cpp ../_public.cpp -lm -lc

tcpselect:
	g++ -g -o tcpselect tcpselect.cpp ../_public.cpp -lm -lc

tcppoll:
	g++ -g -o tcppoll tcppoll.cpp ../_public.cpp -lm -lc

tcpepoll:
	g++ -g -o tcpepoll tcpepoll.cpp ../_public.cpp -lm -lc